image:
  file: .gitpod.dockerfile
tasks:
  - init: . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh
    env:
      SECRET_KEY: e7sz(%i+2-2%#$1n1lz$trw$7o(2_4xb0bd))z-mog*+3=fvfo
    command: echo $SECRET_KEY
    command: /home/gitpod/.pg_ctl/bin/pg_start > /dev/null
  - command: . ${GITPOD_REPO_ROOT}/.vscode/uptime.sh &
    
  
vscode:
  extensions:
    - ms-python.python
    - formulahendry.auto-close-tag
    - eventyret.bootstrap-4-cdn-snippet
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
